Repository cboard-org/cboard-ai-builder, pull requests merged in 2024-08, with the labels that each got.

#173 Feature/download board as cboard json
  src/app/[locale]/dashboard/[id]/@board/Toolbar.tsx
  src/lib/exportHelpers/cboardExportAdapter.ts
  src/lib/exportHelpers/constants.ts
Labels: enhancement

#191 Refactor/layout styles
  src/app/[locale]/dashboard/[id]/@board/InitialContent.tsx
  src/app/[locale]/dashboard/[id]/@board/styles.ts
  src/app/[locale]/dashboard/[id]/@promptForm/GridSizeSelect.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/styles.ts
  src/app/[locale]/dashboard/[id]/@savedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/layout.tsx
  src/app/[locale]/dashboard/[id]/styles.ts
  src/intl/cbuilder.json
  src/stores/prompt-slice.ts
  src/theme.ts
Labels: enhancement

#193 Feature/add dark mode
  src/app/[locale]/dashboard/[id]/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/[id]/@board/InitialContent.tsx
  src/app/[locale]/dashboard/[id]/@board/styles.ts
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/styles.ts
  src/app/[locale]/dashboard/[id]/@savedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/layout.tsx
  src/app/[locale]/globals.css
  src/app/[locale]/layout.tsx
  src/components/PictogramEditor/styles.ts
  src/components/Settings/AppSection.tsx
  src/components/Settings/styles.ts
  src/components/Symbol/GenerateIcon.tsx
  src/components/Symbol/Symbol.tsx
  src/components/TileEditorModal/EmblaCarouselThumbsButton.tsx
  src/components/TileEditorModal/TileEditor.tsx
  src/intl/cbuilder.json
  src/providers/ThemeProvider.tsx
  src/stores/dashboard-slice.ts
  src/theme.ts
Labels: enhancement

#186 Await the generatePicto function on deep generate click
  src/components/TileEditorModal/TileEditor.tsx
  src/components/TileEditorModal/TileEditorModal.tsx
Labels: fix

#183 Use prompt as name for the board
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
  src/lib/cboard-ai-engine/cboard-adapter.ts
  src/lib/exportHelpers/cboardExportAdapter.ts
Labels: fix

#197 Fixed Error handling for the whole project
  src/app/[locale]/dashboard/[id]/@board/Toolbar.tsx
  src/app/[locale]/dashboard/[id]/@board/useSaveOnSetBoard.ts
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
  src/app/api/leonardo/generations/[generationId]/route.ts
  src/app/api/leonardo/generations/route.ts
  src/app/api/mymidjourney/button/route.ts
  src/app/api/mymidjourney/imagine/route.ts
  src/app/api/mymidjourney/message/[messageId]/route.ts
  src/common/common.ts
  src/components/Tile/Tile.tsx
  src/components/TileEditorModal/TileEditor.tsx
  src/lib/ai-picto/picto.ts
  src/lib/next-auth/config.ts
  src/providers/StoreProvider.tsx
  src/stores/board-slice.ts
  yarn.lock
Labels: refactor
