Repository cboard-org/cboard-ai-builder, pull requests merged in 2024-03, with the labels that each got.

#67 Feature/combine context providers
  src/app/[locale]/layout.tsx
  src/components/DataItem/DataItem.tsx
  src/providers/BoardStoreProvider.tsx
  src/providers/PromptStoreProvider.tsx
  src/providers/StoreProvider.tsx
  src/stores/board-store.ts
  src/utils/combineComponents.tsx
  tsconfig.json
Labels: enhancement

#68 Edit the Primary color of Mui Theme
  src/theme.ts
Labels: bug

#74 Feature/Render the board after submit PromptForm
  src/app/[locale]/dashboard/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/@promptForm/actions.tsx
  src/stores/board-store.ts
Labels: enhancement

#71 Feature/Show updated prompt values on edit click and example click
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/stores/prompt-store.ts
Labels: enhancement

#86 Feature / Implement engine v1.2
  .env
  .env.development
  package.json
  src/app/[locale]/dashboard/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/@promptForm/actions.tsx
  src/components/Symbol/Symbol.tsx
  src/components/Tile/Tile.tsx
  src/lib/cboard-ai-engine/cboard-adapter.ts
  src/stores/board-slice.ts
  yarn.lock
Labels: enhancement

#93 Feature/show initial board UI
  src/app/[locale]/dashboard/@board/layout.tsx
  src/app/[locale]/dashboard/@board/page.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/stores/board-slice.ts
Labels: enhancement

#92 Improve application messages
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/@navbar/page.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/app/[locale]/signin/Signin.tsx
  src/intl/dictionaries/en-US.json
  src/intl/dictionaries/pt-BR.json
Labels: enhancement

#98 Improve / Change colors
  src/app/[locale]/dashboard/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/styles.module.css
  src/app/[locale]/globals.css
  src/lib/cboard-ai-engine/cboard-adapter.ts
Labels: ui

#99 Feature/persist the store
  src/app/[locale]/dashboard/@board/page.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/providers/StoreProvider.tsx
  src/stores/board-slice.ts
Labels: enhancement

#102 Fix/credentials singin success redirect
  src/app/[locale]/signin/Login/Dialog.tsx
Labels: fix

#69 Feature - Add mongoose
  .env
  .env.development
  package.json
  src/app/[locale]/dashboard/@board/types.ts
  src/app/[locale]/dashboard/@promptForm/actions.tsx
  src/db/services/Board/model.ts
  src/db/services/Board/service.ts
  src/db/services/Prompt/model.ts
  src/db/services/Prompt/service.ts
  src/db/utils/helpers.ts
  src/lib/dbConnect.ts
  yarn.lock
Labels: enhancement

#101 Feature/Preprare the Entire PromptForm to be a controlled component
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/@promptForm/GridSizeSelect.tsx
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/stores/prompt-slice.ts
Labels: enhancement

#116 Fix / Decouple UI from DB
  src/app/[locale]/dashboard/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/@board/Grid/Grid.tsx
  src/app/[locale]/dashboard/@board/Grid/gridManipulation.ts
  src/app/[locale]/dashboard/@board/Grid/types.ts
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/@history/actions.ts
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/@promptForm/actions.tsx
  src/app/[locale]/dashboard/@savedBoards/actions.ts
  src/commonTypes/Board.ts
  src/commonTypes/Grid.ts
  src/commonTypes/Prompt.ts
  src/commonTypes/Tile.ts
  src/components/DataItem/DataItem.tsx
  src/components/Symbol/Symbol.tsx
  src/components/Tile/Tile.tsx
  src/db/services/Board/model.ts
  src/db/services/Prompt/model.ts
  src/db/services/Prompt/service.ts
  src/lib/cboard-ai-engine/cboard-adapter.ts
  src/stores/board-slice.ts
  src/stores/prompt-slice.ts
Labels: fix, refactor

#118 Feature/prevent change board on board generation
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/components/DataItem/DataItem.tsx
  src/providers/StoreProvider.tsx
  src/stores/dashboard-slice.ts
Labels: enhancement

#119 Feature/use pathname params on dashboard
  src/app/[locale]/dashboard/[id]/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/[id]/@board/BoardPage.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/DefaultEmptyCell/DefaultEmptyCell.module.css
  src/app/[locale]/dashboard/[id]/@board/Grid/DefaultEmptyCell/DefaultEmptyCell.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/DraggableItem/DraggableItem.module.css
  src/app/[locale]/dashboard/[id]/@board/Grid/DraggableItem/DraggableItem.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/DroppableCell/DroppableCell.module.css
  src/app/[locale]/dashboard/[id]/@board/Grid/DroppableCell/DroppableCell.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/Grid.module.css
  src/app/[locale]/dashboard/[id]/@board/Grid/Grid.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/Row/Row.module.css
  src/app/[locale]/dashboard/[id]/@board/Grid/Row/Row.tsx
  src/app/[locale]/dashboard/[id]/@board/Grid/gridManipulation.ts
  src/app/[locale]/dashboard/[id]/@board/Grid/index.ts
  src/app/[locale]/dashboard/[id]/@board/Grid/types.ts
  src/app/[locale]/dashboard/[id]/@board/InitialContent.tsx
  src/app/[locale]/dashboard/[id]/@board/Toolbar.tsx
  src/app/[locale]/dashboard/[id]/@board/constants.ts
  src/app/[locale]/dashboard/[id]/@board/page.tsx
  src/app/[locale]/dashboard/[id]/@board/styles.ts
  src/app/[locale]/dashboard/[id]/@board/testBoard.json
  src/app/[locale]/dashboard/[id]/@history/HistoryList.tsx
  src/app/[locale]/dashboard/[id]/@history/actions.ts
  src/app/[locale]/dashboard/[id]/@history/error.tsx
  src/app/[locale]/dashboard/[id]/@history/loading.tsx
  src/app/[locale]/dashboard/[id]/@history/page.tsx
  src/app/[locale]/dashboard/[id]/@navbar/page.tsx
  src/app/[locale]/dashboard/[id]/@navbar/styles.module.css
  src/app/[locale]/dashboard/[id]/@promptForm/GridSizeSelect.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/icons.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/page.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/SavedBoardList.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/actions.ts
  src/app/[locale]/dashboard/[id]/@savedBoards/error.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/loading.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/page.tsx
  src/app/[locale]/dashboard/[id]/SavedData/SavedData.tsx
  src/app/[locale]/dashboard/[id]/SavedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/layout.tsx
  src/app/[locale]/dashboard/[id]/page.tsx
  src/app/[locale]/dashboard/[id]/styles.module.css
  src/app/[locale]/dashboard/page.tsx
  src/app/[locale]/signin/Login/Dialog.tsx
  src/app/[locale]/signin/constants.ts
  src/lib/cboard-ai-engine/cboard-adapter.ts
  src/stores/board-slice.ts
  tsconfig.json
Labels: enhancement
