Repository cboard-org/cboard-ai-builder, pull requests merged in 2024-04, with the labels that each got.

#127 Use ref to prevent blink animation on submit
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
Labels: bug

#126 Feature/Manage views and URLs
  src/app/[locale]/dashboard/[id]/@board/BoardPage.tsx
  src/app/[locale]/dashboard/[id]/@board/error.tsx
  src/app/[locale]/dashboard/[id]/@board/loading.tsx
  src/app/[locale]/dashboard/[id]/@board/page.tsx
  src/app/[locale]/dashboard/[id]/@history/page.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/error.tsx
  src/app/[locale]/dashboard/[id]/@savedBoards/page.tsx
  src/app/[locale]/dashboard/[id]/@savedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/@savedData/error.tsx
  src/app/[locale]/dashboard/[id]/@savedData/loading.tsx
  src/app/[locale]/dashboard/[id]/@savedData/page.tsx
  src/app/[locale]/dashboard/[id]/SavedData/SavedData.tsx
  src/app/[locale]/dashboard/[id]/SavedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/constants.ts
  src/app/[locale]/dashboard/[id]/history/History.tsx
  src/app/[locale]/dashboard/[id]/history/actions.ts
  src/app/[locale]/dashboard/[id]/layout.tsx
  src/app/[locale]/dashboard/[id]/page.tsx
  src/app/[locale]/dashboard/[id]/savedBoards/SavedBoardList.tsx
  src/app/[locale]/dashboard/[id]/savedBoards/actions.ts
  src/components/DataItem/DataItem.tsx
  src/components/DataList/DataList.tsx
  src/components/IntlWrapperForAsync/IntlWrapperForAsync.tsx
  src/providers/StoreProvider.tsx
  src/stores/board-slice.ts
  src/stores/dashboard-slice.ts
  src/stores/prompt-slice.ts
Labels: enhancement

#125 Feature / Soft delete prompt
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
  src/app/[locale]/dashboard/[id]/@savedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/@savedData/page.tsx
  src/app/[locale]/dashboard/[id]/history/History.tsx
  src/app/[locale]/dashboard/[id]/history/HistoryList.tsx
  src/app/[locale]/dashboard/[id]/history/actions.ts
  src/app/[locale]/dashboard/[id]/savedBoards/SavedBoardList.tsx
  src/components/DataItem/DataItem.tsx
  src/components/DataList/DataList.tsx
  src/db/services/Prompt/model.ts
  src/db/services/Prompt/service.ts
Labels: enhancement, refactor

#131 Fix/Remove navigating with native history API
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@savedData/TabsSelector.tsx
  src/app/[locale]/dashboard/[id]/page.tsx
  src/app/[locale]/dashboard/[id]/savedBoards/SavedBoardList.tsx
  src/components/DataItem/DataItem.tsx
  src/components/DataList/DataList.tsx
  src/providers/StoreProvider.tsx
  src/stores/dashboard-slice.ts
Labels: bug

#134 Feature/next image component for symbols
  .env
  next.config.js
  src/app/[locale]/dashboard/[id]/@board/testBoard.json
  src/components/Symbol/Symbol.tsx
Labels: enhancement

#143 Fix/avoid use store to show initial content
  src/app/[locale]/dashboard/[id]/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/[id]/@board/BoardPage.tsx
  src/app/[locale]/dashboard/[id]/@board/InitialContent.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/usePromptBlinkAnimation.ts
  src/providers/StoreProvider.tsx
  src/stores/board-slice.ts
Labels: bug

#149 Feature/save a board
  src/app/[locale]/dashboard/[id]/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/[id]/@board/Toolbar.tsx
  src/app/[locale]/dashboard/[id]/@board/actions.ts
  src/app/[locale]/dashboard/[id]/@board/page.tsx
  src/app/[locale]/dashboard/[id]/@board/useSaveOnSetBoard.ts
  src/app/[locale]/dashboard/[id]/savedBoards/actions.ts
  src/commonTypes/Board.ts
  src/components/DataItem/DataItem.tsx
  src/db/services/Board/model.ts
  src/db/services/Board/service.ts
  src/lib/cboard-ai-engine/cboard-adapter.ts
  src/stores/board-slice.ts
Labels: enhancement

#147 Feature / Add Pictonizer switch funtionality
  src/app/[locale]/dashboard/[id]/@board/BoardContainer.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
  src/components/Symbol/GenerateButton.tsx
  src/components/Symbol/Symbol.module.css
  src/components/Symbol/Symbol.tsx
Labels: enhancement

#150 Add Branding and styles to InitialContent.tsx and PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@board/InitialContent.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/[id]/@promptForm/styles.ts
  src/app/[locale]/dashboard/[id]/layout.tsx
Labels: enhancement

#154 Feature/contentSafe
  .env
  .env.development
  src/app/[locale]/dashboard/[id]/@promptForm/actions.tsx
Labels: enhancement
