Repository cboard-org/cboard-ai-builder, pull requests merged in 2024-02, with the labels that each got.

#48 Improve prompt styles
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
Labels: ui

#45 Feature/reusable pagination on SavedData
  src/app/[locale]/dashboard/@history/HistoryList.tsx
  src/app/[locale]/dashboard/@history/error.tsx
  src/app/[locale]/dashboard/@savedBoards/SavedBoardList.tsx
  src/app/[locale]/dashboard/@savedBoards/actions.ts
  src/app/[locale]/dashboard/@savedBoards/error.tsx
  src/app/[locale]/dashboard/@savedBoards/loading.tsx
  src/app/[locale]/dashboard/@savedBoards/page.tsx
  src/app/[locale]/dashboard/SavedData/SavedData.tsx
  src/app/[locale]/dashboard/SavedData/TabsSelector.tsx
  src/app/[locale]/dashboard/layout.tsx
  src/components/DataItem/DataItem.tsx
  src/components/DataList/DataList.tsx
  src/components/DataList/styles.ts
  src/components/ErrorAndReset/ErrorAndReset.tsx
  src/components/ErrorAndReset/styles.ts
  src/intl/dictionaries/en-US.json
Labels: ui

#49 Creates UI for signIn page integrating with OAuth
  public/images/boards-example-cut.png
  public/images/boards-example.png
  src/app/[locale]/dashboard/@navbar/page.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/signin/Login/Dialog.tsx
  src/app/[locale]/signin/Login/Login.tsx
  src/app/[locale]/signin/Login/styles.ts
  src/app/[locale]/signin/OAuth/Button.tsx
  src/app/[locale]/signin/OAuth/styles.ts
  src/app/[locale]/signin/Signin.tsx
  src/app/[locale]/signin/constants.ts
  src/app/[locale]/signin/page.tsx
  src/app/[locale]/signin/styles.ts
  src/components/InternalLink/InternalLink.tsx
  src/components/icons/Apple.tsx
  src/components/icons/Brand.tsx
  src/components/icons/Facebook.tsx
  src/components/icons/Google.tsx
  src/intl/dictionaries/en-US.json
  src/lib/cboard-api/auth.ts
  src/lib/next-auth/config.ts
  src/middleware.ts
Labels: ui

#60 Feature/improve examples text areas
  src/app/[locale]/dashboard/@board/InitialContent.tsx
  src/app/[locale]/dashboard/@board/styles.ts
Labels: enhancement

#57 Feature/add zustand store for prompt store
  README.md
  package.json
  src/app/[locale]/dashboard/@history/HistoryList.tsx
  src/app/[locale]/dashboard/@history/actions.ts
  src/app/[locale]/dashboard/@promptForm/PromptForm.tsx
  src/app/[locale]/dashboard/@savedBoards/SavedBoardList.tsx
  src/app/[locale]/dashboard/@savedBoards/actions.ts
  src/app/[locale]/dashboard/types.ts
  src/app/[locale]/layout.tsx
  src/components/DataItem/DataItem.tsx
  src/providers/prompt-store-provider.tsx
  src/stores/prompt-store.ts
  yarn.lock
Labels: enhancement, help wanted, ui
